---
- name: Configure extensions
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false
  vars:
    install_substring: "was successfully installed."
    ext_id: "ms-python.python@2024.12.3"
  tasks:
    - name: Install last known working Python Extension version
      ansible.builtin.command: "code-oss --install-extension '{{ ext_id }}'"
      register: result
      changed_when: install_substring in result.stdout
